# Generated by Django 4.2.8 on 2023-12-06 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Economics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default='default.jpg', upload_to='business_covers/')),
                ('title', models.CharField(default='unknown', max_length=200)),
                ('author_name', models.CharField(default='unknown', max_length=200)),
                ('author_img', models.ImageField(default='default.jpg', upload_to='business_authors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desc_par1', models.TextField()),
                ('desc_par2', models.TextField()),
                ('desc_par3', models.TextField()),
                ('details_title', models.CharField(default='unknown', max_length=200)),
                ('details_quote', models.CharField(default='unknown', max_length=200)),
                ('details_par1', models.TextField()),
                ('details_par2', models.TextField()),
                ('details_par3', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default='default.jpg', upload_to='business_covers/')),
                ('title', models.CharField(default='unknown', max_length=200)),
                ('author_name', models.CharField(default='unknown', max_length=200)),
                ('author_img', models.ImageField(default='default.jpg', upload_to='business_authors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desc_par1', models.TextField()),
                ('desc_par2', models.TextField()),
                ('desc_par3', models.TextField()),
                ('details_title', models.CharField(default='unknown', max_length=200)),
                ('details_quote', models.CharField(default='unknown', max_length=200)),
                ('details_par1', models.TextField()),
                ('details_par2', models.TextField()),
                ('details_par3', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unknown', max_length=200)),
                ('Img', models.ImageField(default='default.jpg', upload_to='business_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default='default.jpg', upload_to='business_covers/')),
                ('title', models.CharField(default='unknown', max_length=200)),
                ('author_name', models.CharField(default='unknown', max_length=200)),
                ('author_img', models.ImageField(default='default.jpg', upload_to='business_authors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desc_par1', models.TextField()),
                ('desc_par2', models.TextField()),
                ('desc_par3', models.TextField()),
                ('details_title', models.CharField(default='unknown', max_length=200)),
                ('details_quote', models.CharField(default='unknown', max_length=200)),
                ('details_par1', models.TextField()),
                ('details_par2', models.TextField()),
                ('details_par3', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Politics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default='default.jpg', upload_to='business_covers/')),
                ('title', models.CharField(default='unknown', max_length=200)),
                ('author_name', models.CharField(default='unknown', max_length=200)),
                ('author_img', models.ImageField(default='default.jpg', upload_to='business_authors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desc_par1', models.TextField()),
                ('desc_par2', models.TextField()),
                ('desc_par3', models.TextField()),
                ('details_title', models.CharField(default='unknown', max_length=200)),
                ('details_quote', models.CharField(default='unknown', max_length=200)),
                ('details_par1', models.TextField()),
                ('details_par2', models.TextField()),
                ('details_par3', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technoloy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default='default.jpg', upload_to='business_covers/')),
                ('title', models.CharField(default='unknown', max_length=200)),
                ('author_name', models.CharField(default='unknown', max_length=200)),
                ('author_img', models.ImageField(default='default.jpg', upload_to='business_authors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desc_par1', models.TextField()),
                ('desc_par2', models.TextField()),
                ('desc_par3', models.TextField()),
                ('details_title', models.CharField(default='unknown', max_length=200)),
                ('details_quote', models.CharField(default='unknown', max_length=200)),
                ('details_par1', models.TextField()),
                ('details_par2', models.TextField()),
                ('details_par3', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='business',
            name='time',
        ),
        migrations.AddField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='author_img',
            field=models.ImageField(default='default.jpg', upload_to='business_authors/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='business_covers/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
