# Generated by Django 4.2.8 on 2023-12-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0003_todaypost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worldnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default='default.jpg', upload_to='business_covers/')),
                ('title', models.CharField(default='unknown', max_length=200)),
                ('author_name', models.CharField(default='unknown', max_length=200)),
                ('author_img', models.ImageField(default='default.jpg', upload_to='business_authors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desc_par1', models.TextField()),
                ('desc_par2', models.TextField()),
                ('desc_par3', models.TextField()),
                ('details_title', models.CharField(default='unknown', max_length=200)),
                ('details_quote', models.CharField(default='unknown', max_length=200)),
                ('details_par1', models.TextField()),
                ('details_par2', models.TextField()),
                ('details_par3', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
