# Generated by Django 4.2.8 on 2023-12-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0004_worldnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldnews',
            name='cat',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
